### ISSUE TITLE
Crash in WebSocket.swift with iOS 7

### ISSUE THREAD

**Issue by sovannarithsok** [socketio/socket.io-client-swift#116]
@nuclearace  What's the problem between Socket client and Socket server that crash on that.
How do you think about this issue?

![screen shot 2015-07-07 at 8 20 34 am](https://cloud.githubusercontent.com/assets/5999202/8610839/f9abcdfc-26e1-11e5-87fe-86dcb923dae8.png)

**Comment by nuclearace** [comment]
I've never seen a crash there. What are the sircumstances?

**Comment by sovannarithsok** [comment]
@nuclearace I have problem  with iPhone 5 with UInt64 above . if I change to UInt32, it's not crash but the socket is always loop with connect and disconnect.

**Comment by nuclearace** [comment]
It's hard for me to debug because I don't have an iOS device, and I don't think the new Xcode's have iOS 7 simulators.

**Comment by MihaelIsaev** [comment]
I have crash on this line too, and I catch it only in release mode and only on iPhone 4S

    println(bytes) //works fine
    println(bytes[0]) //crash

How to fix it?(

**Comment by MihaelIsaev** [comment]
I have crash on this line too, and I catch it only in release mode and only on iPhone 4S iOS 8.1.4, on iPad Air iOS 8.1.4 and on simulators it works fine.

    println(bytes) //works fine
    println(bytes[0]) //crash

How to fix it?(

**Comment by nuclearace** [comment]
I can try bumping the version of the WebSocket library

**Comment by MihaelIsaev** [comment]
I fixed it by changing Swift compiler optimization level from Fastest to None

Before
![2015-07-22 14 59 21](https://cloud.githubusercontent.com/assets/1272610/8823978/7d700eba-3082-11e5-8c89-a7bb2e5ae4b6.png)

After
![2015-07-22 14 59 45](https://cloud.githubusercontent.com/assets/1272610/8823980/835d7ef2-3082-11e5-960d-41a5e1eaf367.png)

Is it bad solution for production?

**Comment by nuclearace** [comment]
For production? Probably, and if that fixes it, it's a bug in Swift.

**Comment by MihaelIsaev** [comment]
Yes, compile app without optimization is really bad for release?
Yes, it looks like bug in Swift 1.2, but maybe we can find another way for this part of code which will work fine with Swift 1.2?

**Comment by hanishabsigh** [comment]
I'm seeing this issue as well. We initially thought it might have something to do with unicode characters in our packets. We are debugging it now with our server team but haven't made much progress. It is occurring on an iPhone 5 running 8.1.3.

**Comment by stephensilber** [comment]
Not sure if this is related, but I have a user that gets this crash but only when they are on a wifi network:

```

**Comment by nuclearace** [comment]
Actually might be related to https://github.com/daltoniam/Starscream/issues/77

**Comment by ArfanMirza** [comment]
@MihaelIsaev  thanks.. that is work for me too....

**Comment by stewa** [comment]
With the current master branch this crashes for me too on 32 bit hardware with apps build in Release mode.

**Comment by nuclearace** [comment]
From what I've gathered, this is actually a bug in Swift 1.2. Probably some bad optimization that it's doing. Hopefully it gets fixed in Swift 2

**Comment by nuclearace** [comment]
Can anyone confirm that this is fixed in Swift 2?

**Comment by hanishabsigh** [comment]
I'm still seeing this when compiling with Swift 2.0 and running on a 32-bit device.

**Comment by nuclearace** [comment]
I don't have a 32-bit device to test on, so it's kind of hard for me to debug

**Comment by jaykon** [comment]
the same problem in Swift 2.0 + Xcode 7.
@MihaelIsaev 's way work,but i can't confirm if it have any performance problem.

**Comment by MihaelIsaev** [comment]
@jaykon I have no any performance problems in big application released to the AppStore since August 2015, so you can use this solution without any performance risk

**Comment by sasavranic** [comment]
I have this problem too. Latest socket.io library. iPod touch device. On iPhone 6 work ok

**Comment by sasavranic** [comment]
With: pod 'Socket.IO-Client-Swift', '~> 3.1.4'
I have no this problems, now I'm using latest 4 version

**Comment by sasavranic** [comment]
One more thing, only when I change scheme to Release instead of Debug.
With Debug scheme work correctly

**Comment by nuclearace** [comment]
It's a known bug, currently lowering the optimization level is the only way to fix. It's because of bad optimization on 32 bit devices that the Swift compiler is doing

**Comment by sasavranic** [comment]
Optimisation is lowered...

**Comment by sasavranic** [comment]
Ahhh, my bad!
Pods / Socket.io lib, optimisation must be set to NONE. Not enough to set only for main project.
