### ISSUE TITLE
ios swift socket disconnect repeatedly after lock iPhone

### ISSUE THREAD

**Issue by smartKrunal** [socketio/socket.io-client-swift#855]
When Iphone locked & come back at that time Socket Disconnect repeatedly. after each 10 seconds.
I have put code for socket connect, in disconnect event. so whenever socket disconnect it will connect automatically.
i have taken flag 'isWantToConnect' - work of this flag is without calling closeConnection method, socket disconnected then socket connect again.

```
Initialization:
    var socket = SocketIOClient(socketURL: URL(string: kUrlApi.BaseUrl)!, config: [.log(false),.reconnects(false),.forcePolling(true),.forceWebsockets(true)])
    var isWantToConnect = false

Connection Methods:
    func establishConnection() {
        isWantToConnect =  true
        if let objSocketEngine = SocketIOManager.sharedInstance.socket.engine, objSocketEngine.connected {
            return
        } else {
            socket.connect()
        }
    }

    func closeConnection() {
        isWantToConnect =  false
        guard let objSocketEngine = SocketIOManager.sharedInstance.socket.engine, objSocketEngine.connected else{
            return
        }
        socket.disconnect()
    }

Disconnect Subscriber:
    func addDisconnectHandler() {
        socket.on(clientEvent: .disconnect) { (dataArray, ack) in
            print("Socket Disconnected !!! SocketSid : \(self.socket.sid ?? "") Time : \(Date())")
            if self.isWantToConnect{
                self.perform(#selector(self.establishConnection), with: nil, afterDelay: 0.1)
            }
        }
    }

```
This is logs:

Socket Error !!! SocketSid : 
Socket StatusChange !!! SocketSid : 
Socket StatusChange !!! SocketSid : 
Socket Disconnected !!! SocketSid :  Time : 2017-11-06 08:06:45 +0000
Socket StatusChange !!! SocketSid : 
Socket StatusChange !!! SocketSid : BjnJLzWfWeRSx8IFAABu
Socket Connected Successfully !!! SocketSid : BjnJLzWfWeRSx8IFAABu Time : 2017-11-06 08:06:46 +0000
Socket StatusChange !!! SocketSid : BjnJLzWfWeRSx8IFAABu
Socket StatusChange !!! SocketSid : BjnJLzWfWeRSx8IFAABu
Socket Disconnected !!! SocketSid : BjnJLzWfWeRSx8IFAABu Time : 2017-11-06 08:06:56 +0000
Socket StatusChange !!! SocketSid : 
Socket StatusChange !!! SocketSid : tMPTz3G4vcmODifgAABv
Socket Connected Successfully !!! SocketSid : tMPTz3G4vcmODifgAABv Time : 2017-11-06 08:06:57 +0000
Socket StatusChange !!! SocketSid : tMPTz3G4vcmODifgAABv
Socket StatusChange !!! SocketSid : tMPTz3G4vcmODifgAABv
Socket Disconnected !!! SocketSid : tMPTz3G4vcmODifgAABv Time : 2017-11-06 08:07:07 +0000
Socket StatusChange !!! SocketSid : 
Socket StatusChange !!! SocketSid : DGNxKJ6uH6rnAeusAABw
Socket Connected Successfully !!! SocketSid : DGNxKJ6uH6rnAeusAABw Time : 2017-11-06 08:07:07 +0000
Socket StatusChange !!! SocketSid : DGNxKJ6uH6rnAeusAABw
Socket StatusChange !!! SocketSid : DGNxKJ6uH6rnAeusAABw
Socket Disconnected !!! SocketSid : DGNxKJ6uH6rnAeusAABw Time : 2017-11-06 08:07:18 +0000
Socket StatusChange !!! SocketSid : 
Socket StatusChange !!! SocketSid : fWE8kHldjkxnnDgsAABx
Socket Connected Successfully !!! SocketSid : fWE8kHldjkxnnDgsAABx Time : 2017-11-06 08:07:19 +0000
Socket StatusChange !!! SocketSid : fWE8kHldjkxnnDgsAABx
Socket StatusChange !!! SocketSid : fWE8kHldjkxnnDgsAABx
Socket Disconnected !!! SocketSid : fWE8kHldjkxnnDgsAABx Time : 2017-11-06 08:07:29 +0000
Socket StatusChange !!! SocketSid : 
Socket StatusChange !!! SocketSid : 2FfWJL54HfyvWK62AABy
Socket Connected Successfully !!! SocketSid : 2FfWJL54HfyvWK62AABy Time : 2017-11-06 08:07:29 +0000
Socket StatusChange !!! SocketSid : 2FfWJL54HfyvWK62AABy
Socket StatusChange !!! SocketSid : 2FfWJL54HfyvWK62AABy
Socket Disconnected !!! SocketSid : 2FfWJL54HfyvWK62AABy Time : 2017-11-06 08:07:40 +0000
Socket StatusChange !!! SocketSid : 
Socket StatusChange !!! SocketSid : AZVawjUwtF84VBB8AABz
Socket Connected Successfully !!! SocketSid : AZVawjUwtF84VBB8AABz Time : 2017-11-06 08:07:41 +0000

**Comment by nuclearace** [comment]
If you turn on logging in the client was is printed?

**Comment by nuclearace** [comment]
Also be warned, checking the engine's connected status in this way might not mean the actual socket.io-client is connected, especially if you're using namespaces. And this code will not be compatible with v13, which is going to be a major change to the structure of the library.

**Comment by smartKrunal** [comment]
right now i am using v12. you want to say that, if i am install v13, then this kind of issue may not be occur ?
i cant get exact meaning. what you trying to say. please help me to resolving this issue.

**Comment by smartKrunal** [comment]
```
& This is client logs

2017-11-07 11:22:03.333528+0530 Techne[5209:2753090] [MC] Lazy loading NSBundle MobileCoreServices.framework
2017-11-07 11:22:03.340013+0530 Techne[5209:2753090] [MC] Loaded MobileCoreServices.framework
2017-11-07 11:22:03.351985+0530 Techne[5209:2753090] [MC] System group container for systemgroup.com.apple.configurationprofiles path is /private/var/containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles
2017-11-07 11:22:03.399739+0530 Techne[5209:2753090] LOG SocketIOClient: Adding handler for event: connect
2017-11-07 11:22:03.401355+0530 Techne[5209:2753090] LOG SocketIOClient: Adding handler for event: disconnect
2017-11-07 11:22:03.401799+0530 Techne[5209:2753090] LOG SocketIOClient: Adding handler for event: reconnect
2017-11-07 11:22:03.402135+0530 Techne[5209:2753090] LOG SocketIOClient: Adding handler for event: reconnectAttempt
2017-11-07 11:22:03.402445+0530 Techne[5209:2753090] LOG SocketIOClient: Adding handler for event: statusChange
2017-11-07 11:22:03.402661+0530 Techne[5209:2753090] LOG SocketIOClient: Adding handler for event: error
2017-11-07 11:22:03.405613+0530 Techne[5209:2753090] LOG SocketIOClient: Handling event: statusChange with data: [SocketIO.SocketIOClientStatus]
Socket StatusChange !!! SocketSid : 
2017-11-07 11:22:03.406192+0530 Techne[5209:2753090] LOG SocketIOClient: Adding engine
2017-11-07 11:22:03.410453+0530 Techne[5209:2753227] LOG SocketEngine: Starting engine. Server: http://gifkar.cloudapp.net:7778/
2017-11-07 11:22:03.410693+0530 Techne[5209:2753227] LOG SocketEngine: Handshaking
2017-11-07 11:22:03.701648+0530 Techne[5209:2753227] LOG SocketEngine: Got message: 0{"sid":"oafkcLCFmNDQ9PflAACz","upgrades":[],"pingInterval":10000,"pingTimeout":7000}
2017-11-07 11:22:03.704919+0530 Techne[5209:2753090] LOG SocketIOClient: Engine opened Connect
2017-11-07 11:22:03.704924+0530 Techne[5209:2753227] LOG SocketEngine: Got message: 40
2017-11-07 11:22:03.705181+0530 Techne[5209:2753090] LOG SocketIOClient: Socket connected
2017-11-07 11:22:03.705260+0530 Techne[5209:2753227] LOG SocketIOClient: Should parse message: 0
2017-11-07 11:22:03.705471+0530 Techne[5209:2753090] LOG SocketIOClient: Handling event: statusChange with data: [SocketIO.SocketIOClientStatus]
2017-11-07 11:22:03.705532+0530 Techne[5209:2753227] LOG SocketEngine: Got message: 42["joinRoom",{}]
Socket StatusChange !!! SocketSid : oafkcLCFmNDQ9PflAACz
2017-11-07 11:22:03.705701+0530 Techne[5209:2753227] LOG SocketIOClient: Should parse message: 2["joinRoom",{}]
2017-11-07 11:22:03.705899+0530 Techne[5209:2753227] LOG SocketEngine: Writing ws:  has data: false
2017-11-07 11:22:03.705976+0530 Techne[5209:2753090] LOG SocketIOClient: Handling event: connect with data: ["/"]
2017-11-07 11:22:03.706057+0530 Techne[5209:2753227] LOG SocketEngineWebSocket: Sending ws:  as type: 2
Socket Connected Successfully !!! SocketSid : oafkcLCFmNDQ9PflAACz Time : 2017-11-07 05:52:03 +0000
2017-11-07 11:22:03.710595+0530 Techne[5209:2753090] LOG SocketParser: Parsing 0
2017-11-07 11:22:03.712369+0530 Techne[5209:2753090] LOG SocketParser: Decoded packet as: SocketPacket {type: 0; data: []; id: -1; placeholders: 0; nsp: /}
2017-11-07 11:22:03.712617+0530 Techne[5209:2753090] LOG SocketParser: Parsing 2["joinRoom",{}]
2017-11-07 11:22:03.714691+0530 Techne[5209:2753090] LOG SocketParser: Decoded packet as: SocketPacket {type: 2; data: [joinRoom, {
}]; id: -1; placeholders: -1; nsp: /}
2017-11-07 11:22:03.715987+0530 Techne[5209:2753090] LOG SocketIOClient: Handling event: joinRoom with data: [{
}]
2017-11-07 11:22:03.811730+0530 Techne[5209:2753236] LOG SocketEngine: Got message: 3
2017-11-07 11:22:04.033970+0530 Techne[5209:2753227] [Firebase/Core][I-COR000003] The default Firebase app has not yet been configured. Add [FIRApp configure] to your application initialization. Read more: https://goo.gl/ctyzm8.
2017-11-07 11:22:04.036 Techne[5209] <Error> [Firebase/Core][I-COR000003] The default Firebase app has not yet been configured. Add [FIRApp configure] to your application initialization. Read more: https://goo.gl/ctyzm8.
2017-11-07 11:22:13.485140+0530 Techne[5209:2753090] +[CATransaction synchronize] called within transaction
2017-11-07 11:22:13.485483+0530 Techne[5209:2753090] +[CATransaction synchronize] called within transaction
2017-11-07 11:22:33.027305+0530 Techne[5209:2753236] LOG SocketEngine: Writing ws:  has data: false
2017-11-07 11:22:33.027427+0530 Techne[5209:2753236] LOG SocketEngineWebSocket: Sending ws:  as type: 2
2017-11-07 11:22:33.032048+0530 Techne[5209:2753780] SocketStream write error [0x1c4172d80]: 1 32
2017-11-07 11:22:33.036371+0530 Techne[5209:2753445] [] nw_socket_get_input_frames recvmsg(fd 7, 1024 bytes): [57] Socket is not connected
2017-11-07 11:22:33.056010+0530 Techne[5209:2753236] ERROR SocketEngine: The operation couldn’t be completed. Broken pipe
2017-11-07 11:22:33.062419+0530 Techne[5209:2753090] ERROR SocketIOClient: The operation couldn’t be completed. Broken pipe
2017-11-07 11:22:33.062641+0530 Techne[5209:2753090] LOG SocketIOClient: Handling event: error with data: ["The operation couldn’t be completed. Broken pipe"]
Socket Error !!! SocketSid : 
2017-11-07 11:22:33.062832+0530 Techne[5209:2753090] LOG SocketIOClient: Handling event: statusChange with data: [SocketIO.SocketIOClientStatus]
Socket StatusChange !!! SocketSid : 
2017-11-07 11:22:33.102759+0530 Techne[5209:2753090] LOG SocketIOClient: Disconnected: The operation couldn’t be completed. Broken pipe
2017-11-07 11:22:33.103001+0530 Techne[5209:2753090] LOG SocketIOClient: Handling event: statusChange with data: [SocketIO.SocketIOClientStatus]
Socket StatusChange !!! SocketSid : 
2017-11-07 11:22:33.103329+0530 Techne[5209:2753090] LOG SocketIOClient: Handling event: disconnect with data: ["The operation couldn’t be completed. Broken pipe"]
Socket Disconnected !!! SocketSid :  Time : 2017-11-07 05:52:33 +0000
dataArray : ["The operation couldn’t be completed. Broken pipe"]
2017-11-07 11:22:33.205286+0530 Techne[5209:2753090] LOG SocketIOClient: Handling event: statusChange with data: [SocketIO.SocketIOClientStatus]
Socket StatusChange !!! SocketSid : 
2017-11-07 11:22:33.206116+0530 Techne[5209:2753783] LOG SocketEngine: Starting engine. Server: http://gifkar.cloudapp.net:7778/
2017-11-07 11:22:33.206543+0530 Techne[5209:2753783] LOG SocketEngine: Handshaking
2017-11-07 11:22:33.595150+0530 Techne[5209:2753780] LOG SocketEngine: Got message: 0{"sid":"4zeWffUZbOwJGmD9AAC0","upgrades":[],"pingInterval":10000,"pingTimeout":7000}
2017-11-07 11:22:33.596630+0530 Techne[5209:2753090] LOG SocketIOClient: Engine opened Connect
2017-11-07 11:22:33.596786+0530 Techne[5209:2753090] LOG SocketIOClient: Socket connected
2017-11-07 11:22:33.596867+0530 Techne[5209:2753780] LOG SocketEngine: Got message: 40
2017-11-07 11:22:33.597076+0530 Techne[5209:2753090] LOG SocketIOClient: Handling event: statusChange with data: [SocketIO.SocketIOClientStatus]
Socket StatusChange !!! SocketSid : 4zeWffUZbOwJGmD9AAC0
2017-11-07 11:22:33.597196+0530 Techne[5209:2753780] LOG SocketIOClient: Should parse message: 0
2017-11-07 11:22:33.597293+0530 Techne[5209:2753090] LOG SocketIOClient: Handling event: connect with data: ["/"]
2017-11-07 11:22:33.597358+0530 Techne[5209:2753780] LOG SocketEngine: Got message: 42["joinRoom",{}]
2017-11-07 11:22:33.597470+0530 Techne[5209:2753780] LOG SSocket Connected Successfully !!! SocketSid : 4zeWffUZbOwJGmD9AAC0 Time : 2017-11-07 05:52:33 +0000
2017-11-07 11:22:33.597978+0530 Techne[5209:2753090] LOG SocketParser: Parsing 0
2017-11-07 11:22:33.598176+0530 Techne[5209:2753090] LOG SocketParser: Decoded packet as: SocketPacket {type: 0; data: []; id: -1; placeholders: 0; nsp: /}
ocketIOClient: Should parse message: 2["joinRoom",{}]
2017-11-07 11:22:33.601611+0530 Techne[5209:2753090] LOG SocketParser: Parsing 2["joinRoom",{}]
2017-11-07 11:22:33.602221+0530 Techne[5209:2753090] LOG SocketParser: Decoded packet as: SocketPacket {type: 2; data: [joinRoom, {
}]; id: -1; placeholders: -1; nsp: /}
2017-11-07 11:22:33.602560+0530 Techne[5209:2753090] LOG SocketIOClient: Handling event: joinRoom with data: [{
}]
2017-11-07 11:22:33.602933+0530 Techne[5209:2753780] LOG SocketEngine: Writing ws:  has data: false
2017-11-07 11:22:33.603132+0530 Techne[5209:2753780] LOG SocketEngineWebSocket: Sending ws:  as type: 2
2017-11-07 11:22:33.711453+0530 Techne[5209:2753782] LOG SocketEngine: Got message: 3
2017-11-07 11:22:43.896992+0530 Techne[5209:2753090] LOG SocketIOClient: Handling event: statusChange with data: [SocketIO.SocketIOClientStatus]
Socket StatusChange !!! SocketSid : 4zeWffUZbOwJGmD9AAC0
2017-11-07 11:22:43.897391+0530 Techne[5209:2753090] LOG SocketIOClient: Disconnected: Ping timeout
2017-11-07 11:22:43.897616+0530 Techne[5209:2753090] LOG SocketIOClient: Handling event: statusChange with data: [SocketIO.SocketIOClientStatus]
Socket StatusChange !!! SocketSid : 4zeWffUZbOwJGmD9AAC0
2017-11-07 11:22:43.897948+0530 Techne[5209:2753090] LOG SocketIOClient: Handling event: disconnect with data: ["Ping timeout"]
Socket Disconnected !!! SocketSid : 4zeWffUZbOwJGmD9AAC0 Time : 2017-11-07 05:52:43 +0000
dataArray : ["Ping timeout"]
2017-11-07 11:22:43.898879+0530 Techne[5209:2753780] LOG SocketEngine: Writing ws:  has data: false
2017-11-07 11:22:43.899036+0530 Techne[5209:2753780] LOG SocketEngineWebSocket: Sending ws:  as type: 2
2017-11-07 11:22:43.899377+0530 Techne[5209:2753780] LOG SocketEngine: Engine is being closed.
2017-11-07 11:22:43.901805+0530 Techne[5209:2753780] LOG SocketEngineWebSocket: Sending ws:  as type: 1
2017-11-07 11:22:44.001306+0530 Techne[5209:2753090] LOG SocketIOClient: Handling event: statusChange with data: [SocketIO.SocketIOClientStatus]
Socket StatusChange !!! SocketSid : 
2017-11-07 11:22:44.002472+0530 Techne[5209:2753780] LOG SocketEngine: Starting engine. Server: http://gifkar.cloudapp.net:7778/
2017-11-07 11:22:44.002634+0530 Techne[5209:2753780] LOG SocketEngine: Handshaking
2017-11-07 11:22:44.326579+0530 Techne[5209:2753445] LOG SocketEngine: Got message: 0{"sid":"8iTjaaa2LNiCepZ6AAC1","upgrades":[],"pingInterval":10000,"pingTimeout":7000}
2017-11-07 11:22:44.327654+0530 Techne[5209:2753090] LOG SocketIOClient: Engine opened Connect
2017-11-07 11:22:44.327818+0530 Techne[5209:2753090] LOG SocketIOClient: Socket connected
2017-11-07 11:22:44.328097+0530 Techne[5209:2753090] LOG SocketIOClient: Handling event: statusChange with data: [SocketIO.SocketIOClientStatus]
Socket StatusChange !!! SocketSid : 8iTjaaa2LNiCepZ6AAC1
2017-11-07 11:22:44.328407+0530 Techne[5209:2753090] LOG SocketIOClient: Handling event: connect with data: ["/"]
Socket Connected Successfully !!! SocketSid : 8iTjaaa2LNiCepZ6AAC1 Time : 2017-11-07 05:52:44 +0000
2017-11-07 11:22:44.329052+0530 Techne[5209:2753445] LOG SocketEngine: Got message: 40
2017-11-07 11:22:44.329240+0530 Techne[5209:2753445] LOG SocketIOClient: Should parse message: 0
2017-11-07 11:22:44.329607+0530 Techne[5209:2753090] LOG SocketParser: Parsing 0
2017-11-07 11:22:44.330326+0530 Techne[5209:2753090] LOG SocketParser: Decoded packet as: SocketPacket {type: 0; data: []; id: -1; placeholders: 0; nsp: /}
2017-11-07 11:22:44.329759+0530 Techne[5209:2753445] LOG SocketEngine: Got message: 42["joinRoom",{}]
2017-11-07 11:22:44.330667+0530 Techne[5209:2753445] LOG SocketIOClient: Should parse message: 2["joinRoom",{}]
2017-11-07 11:22:44.330874+0530 Techne[5209:2753090] LOG SocketParser: Parsing 2["joinRoom",{}]
2017-11-07 11:22:44.331446+0530 Techne[5209:2753090] LOG SocketParser: Decoded packet as: SocketPacket {type: 2; data: [joinRoom, {
}]; id: -1; placeholders: -1; nsp: /}
2017-11-07 11:22:44.331742+0530 Techne[5209:2753090] LOG SocketIOClient: Handling event: joinRoom with data: [{
}]
2017-11-07 11:22:44.332108+0530 Techne[5209:2753445] LOG SocketEngine: Writing ws:  has data: false
2017-11-07 11:22:44.332253+0530 Techne[5209:2753445] LOG SocketEngineWebSocket: Sending ws:  as type: 2
2017-11-07 11:22:44.430722+0530 Techne[5209:2753831] LOG SocketEngine: Got message: 3
2017-11-07 11:22:54.897173+0530 Techne[5209:2753090] LOG SocketIOClient: Handling event: statusChange with data: [SocketIO.SocketIOClientStatus]
Socket StatusChange !!! SocketSid : 8iTjaaa2LNiCepZ6AAC1
2017-11-07 11:22:54.897562+0530 Techne[5209:2753090] LOG SocketIOClient: Disconnected: Ping timeout
2017-11-07 11:22:54.897785+0530 Techne[5209:2753090] LOG SocketIOClient: Handling event: statusChange with data: [SocketIO.SocketIOClientStatus]
Socket StatusChange !!! SocketSid : 8iTjaaa2LNiCepZ6AAC1
2017-11-07 11:22:54.898234+0530 Techne[5209:2753090] LOG SocketIOClient: Handling event: disconnect with data: ["Ping timeout"]
Socket Disconnected !!! SocketSid : 8iTjaaa2LNiCepZ6AAC1 Time : 2017-11-07 05:52:54 +0000
dataArray : ["Ping timeout"]
2017-11-07 11:22:54.899276+0530 Techne[5209:2753874] LOG SocketEngine: Writing ws:  has data: false
2017-11-07 11:22:54.899446+0530 Techne[5209:2753874] LOG SocketEngineWebSocket: Sending ws:  as type: 2
2017-11-07 11:22:54.899790+0530 Techne[5209:2753874] LOG SocketEngine: Engine is being closed.
2017-11-07 11:22:54.901329+0530 Techne[5209:2753874] LOG SocketEngineWebSocket: Sending ws:  as type: 1
2017-11-07 11:22:54.999688+0530 Techne[5209:2753090] LOG SocketIOClient: Handling event: statusChange with data: [SocketIO.SocketIOClientStatus]
Socket StatusChange !!! SocketSid : 
2017-11-07 11:22:55.000511+0530 Techne[5209:2753780] LOG SocketEngine: Starting engine. Server: http://gifkar.cloudapp.net:7778/
2017-11-07 11:22:55.000663+0530 Techne[5209:2753780] LOG SocketEngine: Handshaking
2017-11-07 11:22:55.747418+0530 Techne[5209:2753780] LOG SocketEngine: Got message: 0{"sid":"Hdgu9MFUtD2jjHb0AAC2","upgrades":[],"pingInterval":10000,"pingTimeout":7000}
2017-11-07 11:22:55.748439+0530 Techne[5209:2753090] LOG SocketIOClient: Engine opened Connect
2017-11-07 11:22:55.748605+0530 Techne[5209:2753090] LOG SocketIOClient: Socket connected
2017-11-07 11:22:55.748878+0530 Techne[5209:2753090] LOG SocketIOClient: Handling event: statusChange with data: [SocketIO.SocketIOClientStatus]
Socket StatusChange !!! SocketSid : Hdgu9MFUtD2jjHb0AAC2
2017-11-07 11:22:55.749188+0530 Techne[5209:2753090] LOG SocketIOClient: Handling event: connect with data: ["/"]
Socket Connected Successfully !!! SocketSid : Hdgu9MFUtD2jjHb0AAC2 Time : 2017-11-07 05:52:55 +0000
2017-11-07 11:22:55.749817+0530 Techne[5209:2753780] LOG SocketEngine: Got message: 40
2017-11-07 11:22:55.750005+0530 Techne[5209:2753780] LOG SocketIOClient: Should parse message: 0
2017-11-07 11:22:55.750211+0530 Techne[5209:2753090] LOG SocketParser: Parsing 0
2017-11-07 11:22:55.750750+0530 Techne[5209:2753090] LOG SocketParser: Decoded packet as: SocketPacket {type: 0; data: []; id: -1; placeholders: 0; nsp: /}
2017-11-07 11:22:55.750359+0530 Techne[5209:2753780] LOG SocketEngine: Got message: 42["joinRoom",{}]
2017-11-07 11:22:55.751069+0530 Techne[5209:2753780] LOG SocketIOClient: Should parse message: 2["joinRoom",{}]
2017-11-07 11:22:55.751270+0530 Techne[5209:2753090] LOG SocketParser: Parsing 2["joinRoom",{}]
2017-11-07 11:22:55.751869+0530 Techne[5209:2753090] LOG SocketParser: Decoded packet as: SocketPacket {type: 2; data: [joinRoom, {
}]; id: -1; placeholders: -1; nsp: /}
2017-11-07 11:22:55.752165+0530 Techne[5209:2753090] LOG SocketIOClient: Handling event: joinRoom with data: [{
}]
2017-11-07 11:22:55.752528+0530 Techne[5209:2753780] LOG SocketEngine: Writing ws:  has data: false
2017-11-07 11:22:55.752675+0530 Techne[5209:2753780] LOG SocketEngineWebSocket: Sending ws:  as type: 2
2017-11-07 11:22:56.148024+0530 Techne[5209:2753875] LOG SocketEngine: Got message: 3
2017-11-07 11:23:05.897112+0530 Techne[5209:2753090] LOG SocketIOClient: Handling event: statusChange with data: [SocketIO.SocketIOClientStatus]
Socket StatusChange !!! SocketSid : Hdgu9MFUtD2jjHb0AAC2
2017-11-07 11:23:05.897503+0530 Techne[5209:2753090] LOG SocketIOClient: Disconnected: Ping timeout
2017-11-07 11:23:05.897726+0530 Techne[5209:2753090] LOG SocketIOClient: Handling event: statusChange with data: [SocketIO.SocketIOClientStatus]
Socket StatusChange !!! SocketSid : Hdgu9MFUtD2jjHb0AAC2
2017-11-07 11:23:05.898269+0530 Techne[5209:2753090] LOG SocketIOClient: Handling event: disconnect with data: ["Ping timeout"]
Socket Disconnected !!! SocketSid : Hdgu9MFUtD2jjHb0AAC2 Time : 2017-11-07 05:53:05 +0000
dataArray : ["Ping timeout"]
2017-11-07 11:23:05.899311+0530 Techne[5209:2753923] LOG SocketEngine: Writing ws:  has data: false
2017-11-07 11:23:05.899480+0530 Techne[5209:2753923] LOG SocketEngineWebSocket: Sending ws:  as type: 2
2017-11-07 11:23:05.899827+0530 Techne[5209:2753923] LOG SocketEngine: Engine is being closed.
2017-11-07 11:23:05.901404+0530 Techne[5209:2753923] LOG SocketEngineWebSocket: Sending ws:  as type: 1
2017-11-07 11:23:06.000503+0530 Techne[5209:2753090] LOG SocketIOClient: Handling event: statusChange with data: [SocketIO.SocketIOClientStatus]
Socket StatusChange !!! SocketSid : 
2017-11-07 11:23:06.001211+0530 Techne[5209:2753874] LOG SocketEngine: Starting engine. Server: http://gifkar.cloudapp.net:7778/
2017-11-07 11:23:06.001358+0530 Techne[5209:2753874] LOG SocketEngine: Handshaking
2017-11-07 11:23:06.564134+0530 Techne[5209:2753923] LOG SocketEngine: Got message: 0{"sid":"fvxfvfpw1rvy10ndAAC3","upgrades":[],"pingInterval":10000,"pingTimeout":7000}
2017-11-07 11:23:06.565345+0530 Techne[5209:2753090] LOG SocketIOClient: Engine opened Connect
2017-11-07 11:23:06.565518+0530 Techne[5209:2753090] LOG SocketIOClient: Socket connected
2017-11-07 11:23:06.565793+0530 Techne[5209:2753090] LOG SocketIOClient: Handling event: statusChange with data: [SocketIO.SocketIOClientStatus]
Socket StatusChange !!! SocketSid : fvxfvfpw1rvy10ndAAC3
2017-11-07 11:23:06.566105+0530 Techne[5209:2753090] LOG SocketIOClient: Handling event: connect with data: ["/"]
Socket Connected Successfully !!! SocketSid : fvxfvfpw1rvy10ndAAC3 Time : 2017-11-07 05:53:06 +0000
2017-11-07 11:23:06.567737+0530 Techne[5209:2753923] LOG SocketEngine: Got message: 40
2017-11-07 11:23:06.567938+0530 Techne[5209:2753923] LOG SocketIOClient: Should parse message: 0
2017-11-07 11:23:06.568154+0530 Techne[5209:2753090] LOG SocketParser: Parsing 0
2017-11-07 11:23:06.568748+0530 Techne[5209:2753090] LOG SocketParser: Decoded packet as: SocketPacket {type: 0; data: []; id: -1; placeholders: 0; nsp: /}
2017-11-07 11:23:06.568308+0530 Techne[5209:2753923] LOG SocketEngine: Got message: 42["joinRoom",{}]
2017-11-07 11:23:06.569079+0530 Techne[5209:2753923] LOG SocketIOClient: Should parse message: 2["joinRoom",{}]
2017-11-07 11:23:06.569281+0530 Techne[5209:2753090] LOG SocketParser: Parsing 2["joinRoom",{}]
2017-11-07 11:23:06.570032+0530 Techne[5209:2753090] LOG SocketParser: Decoded packet as: SocketPacket {type: 2; data: [joinRoom, {
}]; id: -1; placeholders: -1; nsp: /}
2017-11-07 11:23:06.570336+0530 Techne[5209:2753090] LOG SocketIOClient: Handling event: joinRoom with data: [{
}]
2017-11-07 11:23:06.570716+0530 Techne[5209:2753923] LOG SocketEngine: Writing ws:  has data: false
2017-11-07 11:23:06.570861+0530 Techne[5209:2753923] LOG SocketEngineWebSocket: Sending ws:  as type: 2
2017-11-07 11:23:06.784021+0530 Techne[5209:2753925] LOG SocketEngine: Got message: 3
2017-11-07 11:23:16.896790+0530 Techne[5209:2753090] LOG SocketIOClient: Handling event: statusChange with data: [SocketIO.SocketIOClientStatus]
Socket StatusChange !!! SocketSid : fvxfvfpw1rvy10ndAAC3
2017-11-07 11:23:16.897187+0530 Techne[5209:2753090] LOG SocketIOClient: Disconnected: Ping timeout
2017-11-07 11:23:16.897411+0530 Techne[5209:2753090] LOG SocketIOClient: Handling event: statusChange with data: [SocketIO.SocketIOClientStatus]
Socket StatusChange !!! SocketSid : fvxfvfpw1rvy10ndAAC3
2017-11-07 11:23:16.897745+0530 Techne[5209:2753090] LOG SocketIOClient: Handling event: disconnect with data: ["Ping timeout"]
Socket Disconnected !!! SocketSid : fvxfvfpw1rvy10ndAAC3 Time : 2017-11-07 05:53:16 +0000
dataArray : ["Ping timeout"]
2017-11-07 11:23:16.898608+0530 Techne[5209:2753923] LOG SocketEngine: Writing ws:  has data: false
2017-11-07 11:23:16.898770+0530 Techne[5209:2753923] LOG SocketEngineWebSocket: Sending ws:  as type: 2
2017-11-07 11:23:16.899271+0530 Techne[5209:2753923] LOG SocketEngine: Engine is being closed.
2017-11-07 11:23:16.901291+0530 Techne[5209:2753923] LOG SocketEngineWebSocket: Sending ws:  as type: 1
2017-11-07 11:23:16.999558+0530 Techne[5209:2753090] LOG SocketIOClient: Handling event: statusChange with data: [SocketIO.SocketIOClientStatus]
Socket StatusChange !!! SocketSid : 
2017-11-07 11:23:17.000266+0530 Techne[5209:2753985] LOG SocketEngine: Starting engine. Server: http://gifkar.cloudapp.net:7778/
2017-11-07 11:23:17.000459+0530 Techne[5209:2753985] LOG SocketEngine: Handshaking
2017-11-07 11:23:17.228693+0530 Techne[5209:2753987] LOG SocketEngine: Got message: 0{"sid":"e-wdmHnN_707tVyYAAC4","upgrades":[],"pingInterval":10000,"pingTimeout":7000}
2017-11-07 11:23:17.229756+0530 Techne[5209:2753090] LOG SocketIOClient: Engine opened Connect
2017-11-07 11:23:17.229932+0530 Techne[5209:2753090] LOG SocketIOClient: Socket connected
2017-11-07 11:23:17.230208+0530 Techne[5209:2753090] LOG SocketIOClient: Handling event: statusChange with data: [SocketIO.SocketIOClientStatus]
Socket StatusChange !!! SocketSid : e-wdmHnN_707tVyYAAC4
2017-11-07 11:23:17.230521+0530 Techne[5209:2753090] LOG SocketIOClient: Handling event: connect with data: ["/"]
Socket Connected Successfully !!! SocketSid : e-wdmHnN_707tVyYAAC4 Time : 2017-11-07 05:53:17 +0000
2017-11-07 11:23:17.231355+0530 Techne[5209:2753987] LOG SocketEngine: Got message: 40
2017-11-07 11:23:17.231546+0530 Techne[5209:2753987] LOG SocketIOClient: Should parse message: 0
2017-11-07 11:23:17.231754+0530 Techne[5209:2753090] LOG SocketParser: Parsing 0
2017-11-07 11:23:17.232798+0530 Techne[5209:2753090] LOG SocketParser: Decoded packet as: SocketPacket {type: 0; data: []; id: -1; placeholders: 0; nsp: /}
2017-11-07 11:23:17.231901+0530 Techne[5209:2753987] LOG SocketEngine: Got message: 42["joinRoom",{}]
2017-11-07 11:23:17.233142+0530 Techne[5209:2753987] LOG SocketIOClient: Should parse message: 2["joinRoom",{}]
2017-11-07 11:23:17.233348+0530 Techne[5209:2753090] LOG SocketParser: Parsing 2["joinRoom",{}]
2017-11-07 11:23:17.233924+0530 Techne[5209:2753090] LOG SocketParser: Decoded packet as: SocketPacket {type: 2; data: [joinRoom, {
}]; id: -1; placeholders: -1; nsp: /}
2017-11-07 11:23:17.234216+0530 Techne[5209:2753090] LOG SocketIOClient: Handling event: joinRoom with data: [{
}]
2017-11-07 11:23:17.234613+0530 Techne[5209:2753987] LOG SocketEngine: Writing ws:  has data: false
2017-11-07 11:23:17.234761+0530 Techne[5209:2753987] LOG SocketEngineWebSocket: Sending ws:  as type: 2
2017-11-07 11:23:17.330256+0530 Techne[5209:2753923] LOG SocketEngine: Got message: 3
2017-11-07 11:23:27.896857+0530 Techne[5209:2753090] LOG SocketIOClient: Handling event: statusChange with data: [SocketIO.SocketIOClientStatus]
Socket StatusChange !!! SocketSid : e-wdmHnN_707tVyYAAC4
2017-11-07 11:23:27.897247+0530 Techne[5209:2753090] LOG SocketIOClient: Disconnected: Ping timeout
2017-11-07 11:23:27.897469+0530 Techne[5209:2753090] LOG SocketIOClient: Handling event: statusChange with data: [SocketIO.SocketIOClientStatus]
Socket StatusChange !!! SocketSid : e-wdmHnN_707tVyYAAC4
2017-11-07 11:23:27.897799+0530 Techne[5209:2753090] LOG SocketIOClient: Handling event: disconnect with data: ["Ping timeout"]
Socket Disconnected !!! SocketSid : e-wdmHnN_707tVyYAAC4 Time : 2017-11-07 05:53:27 +0000
dataArray : ["Ping timeout"]
2017-11-07 11:23:27.898657+0530 Techne[5209:2754013] LOG SocketEngine: Writing ws:  has data: false
2017-11-07 11:23:27.898947+0530 Techne[5209:2754013] LOG SocketEngineWebSocket: Sending ws:  as type: 2
2017-11-07 11:23:27.899286+0530 Techne[5209:2754013] LOG SocketEngine: Engine is being closed.
2017-11-07 11:23:27.901191+0530 Techne[5209:2754013] LOG SocketEngineWebSocket: Sending ws:  as type: 1
2017-11-07 11:23:27.999214+0530 Techne[5209:2753090] LOG SocketIOClient: Handling event: statusChange with data: [SocketIO.SocketIOClientStatus]
Socket StatusChange !!! SocketSid : 
2017-11-07 11:23:27.999919+0530 Techne[5209:2754027] LOG SocketEngine: Starting engine. Server: http://gifkar.cloudapp.net:7778/
2017-11-07 11:23:28.000103+0530 Techne[5209:2754027] LOG SocketEngine: Handshaking
2017-11-07 11:23:28.585370+0530 Techne[5209:2753985] LOG SocketEngine: Got message: 0{"sid":"dUQRk_rMwRxaHsT-AAC5","upgrades":[],"pingInterval":10000,"pingTimeout":7000}
2017-11-07 11:23:28.586688+0530 Techne[5209:2753090] LOG SocketIOClient: Engine opened Connect
2017-11-07 11:23:28.586710+0530 Techne[5209:2753985] LOG SocketEngine: Got message: 40
2017-11-07 11:23:28.587045+0530 Techne[5209:2753090] LOG SocketIOClient: Socket connected
2017-11-07 11:23:28.587242+0530 Techne[5209:2753985] LOG SocketIOClient: Should parse message: 0
2017-11-07 11:23:28.587466+0530 Techne[5209:2753090] LOG SocketIOClient: Handling event: statusChange with data: [SocketIO.SocketIOClientStatus]
Socket StatusChange !!! SocketSid : dUQRk_rMwRxaHsT-AAC5
2017-11-07 11:23:28.587859+0530 Techne[5209:2753090] LOG SocketIOClient: Handling event: connect with data: ["/"]
Socket Connected Successfully !!! SocketSid : dUQRk_rMwRxaHsT-AAC5 Time : 2017-11-07 05:53:28 +0000
2017-11-07 11:23:28.588536+0530 Techne[5209:2753090] LOG SocketParser: Parsing 0
2017-11-07 11:23:28.588806+0530 Techne[5209:2753090] LOG SocketParser: Decoded packet as: SocketPacket {type: 0; data: []; id: -1; placeholders: 0; nsp: /}
2017-11-07 11:23:28.589649+0530 Techne[5209:2753985] LOG SocketEngine: Got message: 42["joinRoom",{}]
2017-11-07 11:23:28.589859+0530 Techne[5209:2753985] LOG SocketIOClient: Should parse message: 2["joinRoom",{}]
2017-11-07 11:23:28.590099+0530 Techne[5209:2753090] LOG SocketParser: Parsing 2["joinRoom",{}]
2017-11-07 11:23:28.590165+0530 Techne[5209:2753985]2017-11-07 11:23:28.590743+0530 Techne[5209:2753090] LOG SocketParser: Decoded packet as: SocketPacket {type: 2; data: [joinRoom, {
}]; id: -1; placeholders: -1; nsp: /}
 LOG SocketEngine: Writing ws:  has data: false
2017-11-07 11:23:28.591280+0530 Techne[5209:2753985] LOG SocketEngineWebSocket: Sending ws:  as type: 2
2017-11-07 11:23:28.591333+0530 Techne[5209:2753090] LOG SocketIOClient: Handling event: joinRoom with data: [{
}]
2017-11-07 11:23:28.729923+0530 Techne[5209:2754013] LOG SocketEngine: Got message: 3
2017-11-07 11:23:37.996168+0530 Techne[5209:2754027] LOG SocketEngine: Writing ws:  has data: false
2017-11-07 11:23:37.996518+0530 Techne[5209:2754027] LOG SocketEngineWebSocket: Sending ws:  as type: 2
2017-11-07 11:23:38.218116+0530 Techne[5209:2754088] LOG SocketEngine: Got message: 3
2017-11-07 11:23:38.996349+0530 Techne[5209:2754088] LOG SocketEngine: Writing ws:  has data: false
2017-11-07 11:23:38.996611+0530 Techne[5209:2754088] LOG SocketEngineWebSocket: Sending ws:  as type: 2
2017-11-07 11:23:39.127543+0530 Techne[5209:2754027] LOG SocketEngine: Got message: 3
2017-11-07 11:23:48.996625+0530 Techne[5209:2754126] LOG SocketEngine: Writing ws:  has data: false
2017-11-07 11:23:48.996887+0530 Techne[5209:2754126] LOG SocketEngineWebSocket: Sending ws:  as type: 2
2017-11-07 11:23:49.265750+0530 Techne[5209:2754088] LOG SocketEngine: Got message: 3
2017-11-07 11:23:49.996497+0530 Techne[5209:2754088] LOG SocketEngine: Writing ws:  has data: false
2017-11-07 11:23:49.996760+0530 Techne[5209:2754088] LOG SocketEngineWebSocket: Sending ws:  as type: 2
2017-11-07 11:23:50.186289+0530 Techne[5209:2754126] LOG SocketEngine: Got message: 3
```

**Comment by nuclearace** [comment]
Hm, I wonder if the ping counter is getting messed up with multiple ping asyncs. If you add the .forceNew config does it fix it?

**Comment by nuclearace** [comment]
@smartKrunal I'm saying v13 is going change the way the api is structured. So code like this will break. Just an FYI.

**Comment by smartKrunal** [comment]
so i should pass forceNew(false) or forceNew(true) ?

**Comment by nuclearace** [comment]
`forceNew(true)`. Also you initial config is conflicting. `forcePolling(true)` and `forceWebsockets(true)` Won't do anything together, only one of them should be true. Won't break anything, but forceWebsockets will trump polling.

**Comment by smartKrunal** [comment]
Yo... is Resolved.....
Thank You Very Very Much @nuclearace
Can you please give your email & skype id. Or this is my email id krunal.smartsensesolutions@gmail.com.
You send just simple mail on my id.

**Comment by nuclearace** [comment]
@smartKrunal I don't use skype anymore.

Also, I'll be releasing a v12.1.3 that includes a change that should fix this without `forceNew`.

**Comment by smartKrunal** [comment]
@nuclearace Whenever I am installing pod, The library gives errors & warnings in swift 3. These are not issues, But Suggestion is there from my side, Whenever you Release new build next time, if possible then you cant take this change also.
![screen shot 2017-11-09 at 9 28 28 am](https://user-images.githubusercontent.com/24540961/32590119-a968fede-c53e-11e7-80b6-becfe3d4c84f.png)

**Comment by murad1981** [comment]
the problem still exists even when using .forceNew(true) ... it happens immediately at the moment the iOS app is minimized (by pressing on home button)
